#### Name : SINU S MARIAM
#### Designation : Machine Learning Intern  
#### Organization : COGNIFYZ TECHNOLOGIES
#### Batch Date: 23/06/2024 to 23/09/2024 
#### Task 2 - RESTAURANT RECOMMENTATION
#### Problem Statement:
* Create a restaurant recommendation system based on user preferences.
* Test the recommendation system by providing sample user preferences and evaluating the quality of recommendations.

In [1]:
#importing necessary libraries 
import numpy as np
import pandas as pd
import warnings 
warnings.filterwarnings('ignore')
#importing libraries for visualisation
import matplotlib.pyplot as plt
from matplotlib import style
import seaborn as sns

In [2]:
#importing Data
data_frame = pd.read_csv('C:/Users/COGNIFYZ/dataset/Dataset .csv')

#### Descriptive analysis

In [3]:
# Understanding the dimensions of train data
data_frame.shape

(9551, 21)

In [4]:
# Understanding the Data Variables
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Restaurant ID         9551 non-null   int64  
 1   Restaurant Name       9551 non-null   object 
 2   Country Code          9551 non-null   int64  
 3   City                  9551 non-null   object 
 4   Address               9551 non-null   object 
 5   Locality              9551 non-null   object 
 6   Locality Verbose      9551 non-null   object 
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object 
 10  Average Cost for two  9551 non-null   int64  
 11  Currency              9551 non-null   object 
 12  Has Table booking     9551 non-null   object 
 13  Has Online delivery   9551 non-null   object 
 14  Is delivering now     9551 non-null   object 
 15  Switch to order menu 

In [5]:
#Displaying columns
data_frame.columns

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')

In [6]:
# Show the top 10 Rows of data
data_frame.head(5)

Restaurant ID         Restaurant Name  Country Code              City  \
0        6317637        Le Petit Souffle           162       Makati City   
1        6304287        Izakaya Kikufuji           162       Makati City   
2        6300002  Heat - Edsa Shangri-La           162  Mandaluyong City   
3        6318506                    Ooma           162  Mandaluyong City   
4        6314302             Sambo Kojin           162  Mandaluyong City   

                                             Address  \
0  Third Floor, Century City Mall, Kalayaan Avenu...   
1  Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   
2  Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...   
3  Third Floor, Mega Fashion Hall, SM Megamall, O...   
4  Third Floor, Mega Atrium, SM Megamall, Ortigas...   

                                     Locality  \
0   Century City Mall, Poblacion, Makati City   
1  Little Tokyo, Legaspi Village, Makati City   
2  Edsa Shangri-La, Ortigas, Mandaluyong City   
3      SM Megamall, Ortigas, Mandaluyong City   
4      SM Megamall, Ortigas, Mandaluyong City   

                                    Locality Verbose   Longitude   Latitude  \
0  Century City Mall, Poblacion, Makati City, Mak...  121.027535  14.565443   
1  Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101  14.553708   
2  Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831  14.581404   
3  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475  14.585318   
4  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508  14.584450   

                           Cuisines  ...          Currency Has Table booking  \
0        French, Japanese, Desserts  ...  Botswana Pula(P)               Yes   
1                          Japanese  ...  Botswana Pula(P)               Yes   
2  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)               Yes   
3                   Japanese, Sushi  ...  Botswana Pula(P)                No   
4                  Japanese, Korean  ...  Botswana Pula(P)               Yes   

  Has Online delivery Is delivering now Switch to order menu Price range  \
0                  No                No                   No           3   
1                  No                No                   No           3   
2                  No                No                   No           4   
3                  No                No                   No           4   
4                  No                No                   No           4   

   Aggregate rating  Rating color Rating text Votes  
0               4.8    Dark Green   Excellent   314  
1               4.5    Dark Green   Excellent   591  
2               4.4         Green   Very Good   270  
3               4.9    Dark Green   Excellent   365  
4               4.8    Dark Green   Excellent   229  

[5 rows x 21 columns]

In [7]:
# Checking for any Duplicated Entries
data_frame.duplicated().sum()

0

In [8]:
#Detecting missing values
data_frame.isna().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [9]:
# Drop null values
data_frame = data_frame.dropna()

In [10]:
# Identifing Categorical(Non-Numerical) Columns in Dataset
data_frame_cat=data_frame.select_dtypes(exclude=['float64','int64'])
data_frame_cat.columns

Index(['Restaurant Name', 'City', 'Address', 'Locality', 'Locality Verbose',
       'Cuisines', 'Currency', 'Has Table booking', 'Has Online delivery',
       'Is delivering now', 'Switch to order menu', 'Rating color',
       'Rating text'],
      dtype='object')

In [11]:
# Identifing Numerical Columns in Dataset
data_frame_num=data_frame.select_dtypes(include=['float64','int64'])
data_frame_num.columns

Index(['Restaurant ID', 'Country Code', 'Longitude', 'Latitude',
       'Average Cost for two', 'Price range', 'Aggregate rating', 'Votes'],
      dtype='object')

In [12]:
# Find Unique values in each Categorical column and their count
cat_cols=['Restaurant Name', 'City', 'Address', 'Locality', 'Locality Verbose',
       'Cuisines', 'Currency', 'Has Table booking', 'Has Online delivery',
       'Is delivering now', 'Switch to order menu', 'Rating color',
       'Rating text']
def num_count():
    for col in cat_cols:
        print('Name of the variable :', col)
        print(data_frame[col].value_counts(), '\n\n')
num_count()

Name of the variable : Restaurant Name
Cafe Coffee Day             83
Domino's Pizza              79
Subway                      63
Green Chick Chop            51
McDonald's                  48
                            ..
The Town House Cafe          1
The G.T. Road                1
The Darzi Bar & Kitchen      1
Smoke On Water               1
Walter's Coffee Roastery     1
Name: Restaurant Name, Length: 7437, dtype: int64 


Name of the variable : City
New Delhi         5473
Gurgaon           1118
Noida             1080
Faridabad          251
Ghaziabad           25
                  ... 
Lincoln              1
Lakeview             1
Lakes Entrance       1
Inverloch            1
Panchkula            1
Name: City, Length: 140, dtype: int64 


Name of the variable : Address
Dilli Haat, INA, New Delhi                                                   11
Sector 41, Noida                                                             11
Greater Kailash (GK) 1, New Delhi                     


* Here Recommendation system is developed using Content-Based Filtering System.
* Dataset does not contain user information,So Restaurant recommendation system is based on features of restaurants themselves.
* We are trying to Recommend restaurants that have similar 'Cuisine Types' with highest ratings in a preferred City.
* All columns except -'Cuisines', 'City','Aggregate rating', 'Rating text' can be dropped from further analysis.      



In [13]:
#Dropping unwanted Columns from data
data_frame.drop(columns=['Restaurant ID', 'Country Code', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range','Rating color','Votes'], inplace=True )

In [14]:
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9542 entries, 0 to 9550
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Restaurant Name   9542 non-null   object 
 1   City              9542 non-null   object 
 2   Cuisines          9542 non-null   object 
 3   Aggregate rating  9542 non-null   float64
 4   Rating text       9542 non-null   object 
dtypes: float64(1), object(4)
memory usage: 447.3+ KB


In [15]:
data_frame['Cuisines'].value_counts()

North Indian                                             936
North Indian, Chinese                                    511
Chinese                                                  354
Fast Food                                                354
North Indian, Mughlai                                    334
                                                        ... 
Bengali, Fast Food                                         1
North Indian, Rajasthani, Asian                            1
Chinese, Thai, Malaysian, Indonesian                       1
Bakery, Desserts, North Indian, Bengali, South Indian      1
Italian, World Cuisine                                     1
Name: Cuisines, Length: 1825, dtype: int64

#### Text Cleaning

In [16]:
# Define function for cleaning data
import re # For replacing any text if required

def Pre_process_text(act_string):
    # remove all values other than alphabets
    new_string= re.sub(r'[^a-zA-Z0-9]'," ", act_string)
    # Lowercasing
    new_string = act_string.lower()
    return new_string

#### Content-Based Filtering System
* Recommend restaurants that have similar 'Cuisine Types' with good ratings in a preferred City.


In [17]:
#### Apply TF-ID (Term Frequency-Inverse Document Frequency)
from sklearn.feature_extraction.text import TfidfVectorizer

# # Convert the cuisines,Rating text,City into format that can be used for TF-ID extraction
data_frame['Cuisines_Rating_City'] = data_frame['Cuisines']+ " " + data_frame['Rating text']+ " " + data_frame['City'].astype(str)
data_frame['Cuisines_Rating_City'] =data_frame['Cuisines_Rating_City'] .apply(str)
#Text Cleaning
data_frame['Cuisines_Rating_City'] = data_frame['Cuisines_Rating_City'].apply(Pre_process_text)

#Extract features from  text data using TF-IDF.
X_tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix= X_tfidf.fit_transform(data_frame['Cuisines_Rating_City'])

In [18]:
# Incorporate Aggregate Rating to feature set
#Min-Max Scaling
from sklearn.preprocessing import MinMaxScaler
min_max = MinMaxScaler()
min_max_rating = min_max.fit_transform(data_frame[['Aggregate rating']])
# Combine TF-IDF features with MIn Max Scaled 'Aggregate rating'
features = np.hstack((tfidf_matrix.toarray(), min_max_rating))

#### Similarity Calculation using Cosine Similarity
* To compute similarity between restaurants based on features 'Cosine Similarity metrics' is used here

In [19]:
from sklearn.metrics.pairwise import cosine_similarity

# Compute cosine similarity matrix
cos_dis= cosine_similarity(features,features)
print(cos_dis)

[[1.         0.92375176 0.54670537 ... 0.42168919 0.44252432 0.44252432]
 [0.92375176 1.         0.54726823 ... 0.40760346 0.42774262 0.42774262]
 [0.54670537 0.54726823 1.         ... 0.41460668 0.4366489  0.44252103]
 ...
 [0.42168919 0.40760346 0.41460668 ... 1.         0.5899944  0.67674371]
 [0.44252432 0.42774262 0.4366489  ... 0.5899944  1.         0.82393237]
 [0.44252432 0.42774262 0.44252103 ... 0.67674371 0.82393237 1.        ]]


In [20]:
# Function to get recommendations
def get_recommendations(restaurant_name, cos_dis, data_frame, n=4):
    # Get index of input restaurant
    id = data_frame[data_frame['Restaurant Name'] == restaurant_name].index[0]
    # Cosine similarity scores for input restaurant
    cos_dis_Restaurant = list(enumerate(cos_dis[id]))
    # Arrange in descending order
    cos_dis_Restaurant  = sorted(cos_dis_Restaurant , key=lambda x: x[1], reverse=True)
    # Top n indices of restaurants
    top_id = [i[0] for i in cos_dis_Restaurant [1:n+1]]
    # Return Recommendations
    return data_frame[['Restaurant Name','Cuisines','City','Aggregate rating']].iloc[top_id]

In [21]:
# Print Recommendation for Restauarant similar to 'Rasoi Ghar'
print(get_recommendations("Rasoi Ghar", cos_dis, data_frame))

                      Restaurant Name       Cuisines   City  Aggregate rating
598  Grand Barbeque Buffet Restaurant  Indian, Asian  Dubai               4.4
586                        Rasoi Ghar         Indian  Dubai               4.3
590               Carnival By Tresind         Indian  Dubai               4.9
597     Tresind - Nassima Royal Hotel         Indian  Dubai               4.9


In [22]:
# Print Recommendation for Restauarant similar to 'Y Cafe & Restaurant'
print(get_recommendations("Y Cafe & Restaurant", cos_dis, data_frame))

         Restaurant Name       Cuisines      City  Aggregate rating
864     Kalsang AMA Cafe           Cafe  Dehradun               4.2
854  Y Cafe & Restaurant           Cafe  Dehradun               4.0
859           Razzmatazz           Cafe  Dehradun               3.9
856      First Gear Cafe  Cafe, Chinese  Dehradun               3.9


-------------------------------THE END----------------------------------